name: "agent-wireguard"

services:
  agent-wireguard:
    container_name: "agent-wireguard"
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    privileged: true
    environment:
      - "SERVER_PORT=51820"
    ports:
      - "51820:51820/udp"
      - "7070:7070"
